apiVersion: v1
kind: Secret
metadata:
  name: keda-metric-api-auth-query-d
  namespace: default
data:
  authMode: "YXBpS2V5QXV0aA=="
  apiKey: "U2FtcGxlQXBpS2V5"
  method: "cXVlcnk="
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-metric-api-auth-query-d-credential
  namespace: default
spec:
  secretTargetRef:
    - parameter: authMode
      name: keda-metric-api-auth-query-d
      key: authMode
    - parameter: apiKey
      name: keda-metric-api-auth-query-d
      key: apiKey
    - parameter: method
      name: keda-metric-api-auth-query-d
      key: method
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-scaledobject-q-d
  namespace: default
  labels:
    deploymentName: dummy-api-auth-q-d
spec:
  maxReplicaCount: 4
  pollingInterval: 3  # Optional. Default: 30 seconds
  cooldownPeriod:  5 # Optional. Default: 300 seconds
  scaleTargetRef:
    deploymentName: dummy-api-auth-q-d
    name: dummy-api-auth-q-d
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "1"
        url: "http://localhost:5000/app/apiAuth/query/d/metric/metricid"
        valueLocation: "metric"
      authenticationRef:
        name: keda-metric-api-auth-query-d-credential