apiVersion: v1
kind: Secret
metadata:
  name: keda-metric-api-basic-auth
  namespace: default
data:
  username: "YWRtaW4=" #base64 encoding of username  i.e. admin
  password: "YWRtaW4=" #base64 encoding of password  i.e. admin
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-metric-api-basic-auth-credential
  namespace: default
spec:
  secretTargetRef:
    - parameter: username
      name: keda-metric-api-basic-auth
      key: username
    - parameter: password
      name: keda-metric-api-basic-auth
      key: password
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-scaledobject-b-a
  namespace: default
  labels:
    deploymentName: dummy-base-auth
spec:
  maxReplicaCount: 4
  pollingInterval: 3  # Optional. Default: 30 seconds
  cooldownPeriod:  5 # Optional. Default: 300 seconds
  scaleTargetRef:
    deploymentName: dummy-base-auth
    name: dummy-base-auth
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "1"
        url: "http://localhost:5000/app/basicAuth/metric/metricid"
        valueLocation: "metric"
        authMode: "basic"
      authenticationRef:
        name: keda-metric-api-basic-auth-credential