apiVersion: v1
kind: Secret
metadata:
  name: keda-metric-api-auth-header-d
  namespace: default
data:
  apiKey: "U2FtcGxlQXBpS2V5"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-metric-api-auth-header-d-credential
  namespace: default
spec:
  secretTargetRef:
    - parameter: apiKey
      name: keda-metric-api-auth-header-d
      key: apiKey
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-scaledobject-h-d
  namespace: default
  labels:
    deploymentName: dummy-api-auth-h-d
spec:
  maxReplicaCount: 4
  pollingInterval: 3  # Optional. Default: 30 seconds
  cooldownPeriod:  5 # Optional. Default: 300 seconds
  scaleTargetRef:
    deploymentName: dummy-api-auth-h-d
    name: dummy-api-auth-h-d
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "1"
        url: "http://localhost:5000/app/apiAuth/headers/d/metric/metricid"
        valueLocation: "metric"
        authMode: "apiKey"
      authenticationRef:
        name: keda-metric-api-auth-header-d-credential