apiVersion: v1
kind: Secret
metadata:
  name: keda-metric-api-auth-query-c
  namespace: default
data:
  authMode: "YXBpS2V5QXV0aA=="
  apiKey: "U2FtcGxlQXBpS2V5"
  method: "cXVlcnk="
  keyParamName: "Y3VzdG9tX3BhcmFt"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-metric-api-auth-query-c-credential
  namespace: default
spec:
  secretTargetRef:
    - parameter: authMode
      name: keda-metric-api-auth-query-c
      key: authMode
    - parameter: apiKey
      name: keda-metric-api-auth-query-c
      key: apiKey
    - parameter: method
      name: keda-metric-api-auth-query-c
      key: method
    - parameter: keyParamName
      name: keda-metric-api-auth-query-c
      key: keyParamName
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-scaledobject-q-c
  namespace: default
  labels:
    deploymentName: dummy-api-auth-q-c
spec:
  maxReplicaCount: 4
  pollingInterval: 3  # Optional. Default: 30 seconds
  cooldownPeriod:  5 # Optional. Default: 300 seconds
  scaleTargetRef:
    deploymentName: dummy-api-auth-q-c
    name: dummy-api-auth-q-c
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "1"
        url: "http://localhost:5000/app/apiAuth/query/c/metric/metricid"
        valueLocation: "metric"
      authenticationRef:
        name: keda-metric-api-auth-query-c-credential