apiVersion: v1
kind: Service
metadata:
  name: tlsapp
  labels:
    app: tlsapp
spec:
  ports:
    - port: 6000
      name: "https"
      protocol: TCP
      targetPort: 6000
  selector:
    app: tlsapp
    tier: frontend
  type: LoadBalancer
  externalName: tlsapp.default.svc.cluster.local
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tlsapp
  labels:
    app: tlsapp
spec:
  selector:
    matchLabels:
      app: tlsapp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tlsapp
        tier: frontend
    spec:
      containers:
        - name: master
          image: local/tlsapp
          imagePullPolicy: IfNotPresent
          args:
            - tlsapp
          ports:
            - containerPort: 6000
              name: tlsapp
          resources:
            limits:
              cpu: "0.1"